services:
  database:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgres/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "psql -U ${POSTGRES_USER} -q -d postgres -c \"SELECT 'ready';\""]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  db-data:

